import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import {
  Activity, BookOpen, Boxes, Building2, CheckCircle2, CircleDollarSign,
  ClipboardList, Code2, Copy, FileText, Gauge, Headphones, LogOut, Menu,
  Plus, Search, Server, Settings2, ShieldCheck, Signal, Users, Wifi, WifiOff,
  XCircle,
} from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import type { Database, Json } from "@/integrations/supabase/types";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { Switch } from "@/components/ui/switch";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";

type Tables = Database["public"]["Tables"];
type Customer = Tables["customers"]["Row"];
type Contract = Tables["contracts"]["Row"];
type Plan = Tables["plans"]["Row"];
type Invoice = Tables["invoices"]["Row"];
type Ticket = Tables["tickets"]["Row"];
type Coverage = Tables["coverage"]["Row"];
type ApiLog = Tables["api_logs"]["Row"];
type ViewKey = "dashboard" | "customers" | "contracts" | "plans" | "invoices" | "tickets" | "coverage" | "api" | "logs" | "simulator";

type AppData = {
  customers: Customer[]; contracts: Contract[]; plans: Plan[]; invoices: Invoice[];
  tickets: Ticket[]; coverage: Coverage[]; apiLogs: ApiLog[]; erpOnline: boolean;
};

const emptyData: AppData = { customers: [], contracts: [], plans: [], invoices: [], tickets: [], coverage: [], apiLogs: [], erpOnline: true };
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const date = (value: string | null) => value ? new Intl.DateTimeFormat("pt-BR").format(new Date(`${value.slice(0, 10)}T12:00:00`)) : "—";
const labels: Record<string, string> = { active: "Ativo", inactive: "Inativo", suspended: "Suspenso", cancelled: "Cancelado", prospect: "Lead", pending: "Pendente", open: "Aberta", overdue: "Vencida", paid: "Paga", resolved: "Resolvido", in_progress: "Em andamento", technical: "Técnico", financial: "Financeiro", commercial: "Comercial", installation: "Instalação", cancellation: "Cancelamento", other: "Outro", low: "Baixa", normal: "Normal", high: "Alta", urgent: "Urgente" };

const nav = [
  ["dashboard", "Dashboard", Gauge], ["customers", "Clientes", Users], ["contracts", "Contratos", FileText],
  ["plans", "Planos", Signal], ["invoices", "Faturas", CircleDollarSign], ["tickets", "Chamados", Headphones],
  ["coverage", "Cobertura", Wifi], ["api", "API", Code2], ["logs", "Logs", ClipboardList], ["simulator", "Simulador", Activity],
] as const;

function StatusBadge({ value }: { value: string }) {
  const style = value === "active" || value === "paid" || value === "resolved" ? "bg-success/15 text-success border-success/25" : value === "overdue" || value === "urgent" || value === "cancelled" ? "bg-destructive/10 text-destructive border-destructive/20" : value === "open" || value === "pending" || value === "prospect" ? "bg-warning/15 text-warning-foreground border-warning/25" : "bg-muted text-muted-foreground border-border";
  return <Badge variant="outline" className={style}>{labels[value] ?? value}</Badge>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <div className="grid gap-1.5"><Label>{label}</Label>{children}</div>;
}

function Login({ onReady }: { onReady: () => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setBusy(true);
    const { error } = await supabase.auth.signInWithPassword({ email, password });
    setBusy(false); if (error) toast.error("Não foi possível entrar", { description: error.message }); else onReady();
  };
  const google = async () => {
    const { error } = await supabase.auth.signInWithOAuth({ provider: "google", options: { redirectTo: window.location.origin } });
    if (error) toast.error("Não foi possível entrar com Google");
  };
  return <main className="grid min-h-screen lg:grid-cols-[1.08fr_.92fr]">
    <section className="relative hidden overflow-hidden bg-primary p-12 text-primary-foreground lg:flex lg:flex-col lg:justify-between">
      <div className="flex items-center gap-3 text-sm font-semibold"><span className="grid size-9 place-items-center rounded-md bg-primary-foreground text-primary"><Wifi className="size-5" /></span>TALOS ISP LAB</div>
      <div className="max-w-xl"><p className="mb-4 text-sm font-semibold uppercase text-primary-foreground/70">Ambiente controlado</p><h1 className="text-5xl font-semibold leading-tight">Operações fictícias.<br />Integrações reais.</h1><p className="mt-5 max-w-md text-base leading-7 text-primary-foreground/75">Laboratório seguro para validar fluxos de atendimento, venda e suporte do seu provedor.</p></div>
      <div className="flex gap-5 text-sm text-primary-foreground/70"><span className="flex items-center gap-2"><ShieldCheck className="size-4" />Dados fictícios</span><span className="flex items-center gap-2"><Server className="size-4" />API v1</span></div>
    </section>
    <section className="flex items-center justify-center bg-background px-6 py-12"><div className="w-full max-w-sm"><div className="mb-8 lg:hidden"><div className="flex items-center gap-3 font-semibold"><span className="grid size-9 place-items-center rounded-md bg-primary text-primary-foreground"><Wifi className="size-5" /></span>TALOS ISP LAB</div></div><h2 className="text-3xl font-semibold">Acessar laboratório</h2><p className="mt-2 text-sm text-muted-foreground">Entre com a conta autorizada para gerenciar os dados de teste.</p><form onSubmit={submit} className="mt-8 grid gap-5"><Field label="E-mail"><Input type="email" autoComplete="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="voce@empresa.com" /></Field><Field label="Senha"><Input type="password" autoComplete="current-password" required value={password} onChange={(e) => setPassword(e.target.value)} /></Field><Button disabled={busy} className="w-full">{busy ? "Entrando..." : "Entrar"}</Button></form><div className="my-6 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border" />OU<span className="h-px flex-1 bg-border" /></div><Button variant="outline" className="w-full" onClick={google}><Building2 />Continuar com Google</Button><p className="mt-8 text-center text-xs text-muted-foreground">Somente dados fictícios. Nenhuma cobrança é realizada.</p></div></section>
  </main>;
}

function SidebarContent({ active, setActive, close }: { active: ViewKey; setActive: (v: ViewKey) => void; close?: () => void }) {
  return <div className="flex h-full flex-col bg-sidebar text-sidebar-foreground"><div className="flex h-16 items-center gap-3 border-b border-sidebar-border px-5"><span className="grid size-8 place-items-center rounded-md bg-sidebar-primary text-sidebar-primary-foreground"><Wifi className="size-4" /></span><div><div className="text-sm font-bold">TALOS</div><div className="text-[10px] uppercase text-muted-foreground">ISP Lab</div></div></div><nav className="flex-1 space-y-1 p-3">{nav.map(([key, label, Icon]) => <Button key={key} variant="ghost" className={`w-full justify-start ${active === key ? "bg-sidebar-accent text-sidebar-accent-foreground" : "text-muted-foreground"}`} onClick={() => { setActive(key); close?.(); }}><Icon />{label}</Button>)}</nav><div className="border-t border-sidebar-border p-4"><div className="rounded-md bg-muted p-3"><div className="flex items-center gap-2 text-xs font-medium"><ShieldCheck className="size-4 text-success" />Ambiente de teste</div><p className="mt-1 text-[11px] text-muted-foreground">Sem dados ou cobranças reais</p></div></div></div>;
}

function Stat({ title, value, detail, icon: Icon }: { title: string; value: string | number; detail: string; icon: typeof Users }) {
  return <Card className="rounded-lg shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-muted-foreground">{title}</p><p className="mt-2 text-3xl font-semibold">{value}</p><p className="mt-2 text-xs text-muted-foreground">{detail}</p></div><span className="grid size-10 place-items-center rounded-md bg-accent text-primary"><Icon className="size-5" /></span></div></CardContent></Card>;
}

export function TalosDashboard() {
  const [sessionReady, setSessionReady] = useState(false); const [authenticated, setAuthenticated] = useState(false);
  const [active, setActive] = useState<ViewKey>("dashboard"); const [mobileOpen, setMobileOpen] = useState(false);
  const [data, setData] = useState(emptyData); const [loading, setLoading] = useState(true); const [query, setQuery] = useState("");

  const load = useCallback(async () => {
    setLoading(true);
    const [customers, contracts, plans, invoices, tickets, coverage, apiLogs, settings] = await Promise.all([
      supabase.from("customers").select("*").order("created_at", { ascending: false }), supabase.from("contracts").select("*").order("created_at", { ascending: false }),
      supabase.from("plans").select("*").order("download_mbps"), supabase.from("invoices").select("*").order("due_date", { ascending: false }),
      supabase.from("tickets").select("*").order("created_at", { ascending: false }), supabase.from("coverage").select("*").order("cep"),
      supabase.from("api_logs").select("*").order("created_at", { ascending: false }).limit(100), supabase.from("lab_settings").select("erp_online").eq("id", true).maybeSingle(),
    ]);
    const error = [customers, contracts, plans, invoices, tickets, coverage, apiLogs, settings].find((r) => r.error)?.error;
    if (error) toast.error("Não foi possível carregar o laboratório", { description: error.message });
    setData({ customers: customers.data ?? [], contracts: contracts.data ?? [], plans: plans.data ?? [], invoices: invoices.data ?? [], tickets: tickets.data ?? [], coverage: coverage.data ?? [], apiLogs: apiLogs.data ?? [], erpOnline: settings.data?.erp_online ?? true }); setLoading(false);
  }, []);

  useEffect(() => { void supabase.auth.getSession().then(({ data: auth }) => { setAuthenticated(Boolean(auth.session)); setSessionReady(true); if (auth.session) void load(); }); const { data: listener } = supabase.auth.onAuthStateChange((_event, next) => { setAuthenticated(Boolean(next)); if (next) void load(); }); return () => listener.subscription.unsubscribe(); }, [load]);
  if (!sessionReady) return <div className="grid min-h-screen place-items-center bg-background"><Activity className="size-7 animate-pulse text-primary" /></div>;
  if (!authenticated) return <Login onReady={() => { setAuthenticated(true); void load(); }} />;

  const customerName = (id: string) => data.customers.find((c) => c.id === id)?.name ?? "Cliente";
  const planName = (id: string) => data.plans.find((p) => p.id === id)?.name ?? "Plano";
  const title = nav.find(([key]) => key === active)?.[1] ?? "Dashboard";
  const filteredCustomers = data.customers.filter((c) => `${c.name} ${c.external_id} ${c.cpf ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  const signOut = async () => { await supabase.auth.signOut(); setAuthenticated(false); };
  const toggleErp = async (checked: boolean) => { const { error } = await supabase.from("lab_settings").update({ erp_online: checked }).eq("id", true); if (error) toast.error("Não foi possível alterar o ERP"); else { setData((old) => ({ ...old, erpOnline: checked })); toast.success(checked ? "ERP simulado online" : "ERP simulado offline"); } };

  return <div className="min-h-screen bg-muted/30"><aside className="fixed inset-y-0 left-0 z-30 hidden w-60 border-r border-sidebar-border lg:block"><SidebarContent active={active} setActive={setActive} /></aside><div className="lg:pl-60"><header className="sticky top-0 z-20 flex h-16 items-center gap-4 border-b bg-background/95 px-4 backdrop-blur md:px-7"><Sheet open={mobileOpen} onOpenChange={setMobileOpen}><SheetTrigger asChild><Button variant="outline" size="icon" className="lg:hidden" aria-label="Abrir menu"><Menu /></Button></SheetTrigger><SheetContent side="left" className="w-64 p-0"><SidebarContent active={active} setActive={setActive} close={() => setMobileOpen(false)} /></SheetContent></Sheet><div className="flex-1"><h1 className="text-lg font-semibold">{title}</h1><p className="hidden text-xs text-muted-foreground sm:block">ISP Teste Talos · Ambiente de laboratório</p></div><div className="flex items-center gap-3"><div className={`hidden items-center gap-2 rounded-md px-3 py-1.5 text-xs font-medium sm:flex ${data.erpOnline ? "bg-success/10 text-success" : "bg-destructive/10 text-destructive"}`}>{data.erpOnline ? <CheckCircle2 className="size-3.5" /> : <XCircle className="size-3.5" />}ERP {data.erpOnline ? "online" : "offline"}</div><Button variant="ghost" size="icon" onClick={signOut} aria-label="Sair"><LogOut /></Button></div></header><main className="mx-auto max-w-[1500px] p-4 md:p-7">{loading ? <div className="grid min-h-72 place-items-center"><Activity className="size-7 animate-pulse text-primary" /></div> : active === "dashboard" ? <DashboardView data={data} customerName={customerName} setActive={setActive} toggleErp={toggleErp} /> : active === "customers" ? <CustomersView rows={filteredCustomers} query={query} setQuery={setQuery} reload={load} /> : active === "contracts" ? <ContractsView rows={data.contracts} customerName={customerName} planName={planName} /> : active === "plans" ? <PlansView rows={data.plans} /> : active === "invoices" ? <InvoicesView rows={data.invoices} customerName={customerName} reload={load} /> : active === "tickets" ? <TicketsView rows={data.tickets} customers={data.customers} customerName={customerName} reload={load} /> : active === "coverage" ? <CoverageView rows={data.coverage} plans={data.plans} reload={load} /> : active === "api" ? <ApiView /> : active === "logs" ? <LogsView rows={data.apiLogs} /> : <SimulatorView data={data} toggleErp={toggleErp} />}</main></div></div>;
}

function DashboardView({ data, customerName, setActive, toggleErp }: { data: AppData; customerName: (id: string) => string; setActive: (v: ViewKey) => void; toggleErp: (v: boolean) => void }) {
  const open = data.invoices.filter((i) => i.status === "open"); const overdue = data.invoices.filter((i) => i.status === "overdue"); const activeTickets = data.tickets.filter((t) => ["open", "in_progress"].includes(t.status));
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm text-muted-foreground">Visão geral</p><h2 className="mt-1 text-2xl font-semibold">Operação do laboratório</h2></div><div className="flex items-center gap-3 rounded-md border bg-background px-4 py-2"><div><p className="text-xs font-medium">ERP simulado</p><p className="text-[11px] text-muted-foreground">Afeta as chamadas da API</p></div><Switch checked={data.erpOnline} onCheckedChange={toggleErp} aria-label="Alternar ERP" /></div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat title="Clientes" value={data.customers.length} detail={`${data.customers.filter((c) => c.status === "prospect").length} leads em teste`} icon={Users} /><Stat title="Recebíveis em aberto" value={money.format([...open, ...overdue].reduce((s, i) => s + Number(i.amount), 0))} detail={`${overdue.length} faturas vencidas`} icon={CircleDollarSign} /><Stat title="Chamados ativos" value={activeTickets.length} detail={`${activeTickets.filter((t) => t.priority === "urgent").length} com prioridade urgente`} icon={Headphones} /><Stat title="Chamadas de API" value={data.apiLogs.length} detail="Últimos 100 registros" icon={Activity} /></div><div className="grid gap-6 xl:grid-cols-[1.45fr_.75fr]"><Card className="rounded-lg shadow-sm"><CardHeader className="flex-row items-center justify-between"><CardTitle className="text-base">Faturas recentes</CardTitle><Button variant="ghost" size="sm" onClick={() => setActive("invoices")}>Ver todas</Button></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Fatura</TableHead><TableHead>Cliente</TableHead><TableHead>Vencimento</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Valor</TableHead></TableRow></TableHeader><TableBody>{data.invoices.slice(0, 6).map((row) => <TableRow key={row.id}><TableCell className="font-mono text-xs">{row.external_id}</TableCell><TableCell>{customerName(row.customer_id)}</TableCell><TableCell>{date(row.due_date)}</TableCell><TableCell><StatusBadge value={row.status} /></TableCell><TableCell className="text-right font-medium">{money.format(row.amount)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card><Card className="rounded-lg shadow-sm"><CardHeader><CardTitle className="text-base">Estado dos serviços</CardTitle></CardHeader><CardContent className="space-y-4"><Service name="Banco de dados" ok /><Service name="Autenticação" ok /><Service name="API v1" ok={data.erpOnline} /><Service name="ERP Mock" ok={data.erpOnline} /><div className="border-t pt-4"><p className="text-xs text-muted-foreground">Última atividade</p><p className="mt-1 text-sm font-medium">{data.apiLogs[0] ? `${data.apiLogs[0].method} ${data.apiLogs[0].endpoint}` : "Nenhuma chamada registrada"}</p></div></CardContent></Card></div></div>;
}
function Service({ name, ok }: { name: string; ok: boolean }) { return <div className="flex items-center justify-between text-sm"><span>{name}</span><span className={`flex items-center gap-1.5 text-xs ${ok ? "text-success" : "text-destructive"}`}><span className={`size-2 rounded-full ${ok ? "bg-success" : "bg-destructive"}`} />{ok ? "Operacional" : "Indisponível"}</span></div>; }

function CustomersView({ rows, query, setQuery, reload }: { rows: Customer[]; query: string; setQuery: (v: string) => void; reload: () => Promise<void> }) {
  const [open, setOpen] = useState(false); const [form, setForm] = useState({ name: "", cpf: "", phone: "", email: "", cep: "", city: "São Carlos", state: "SP", neighborhood: "", address: "", number: "" });
  const save = async (event: FormEvent) => { event.preventDefault(); const { error } = await supabase.from("customers").insert({ ...form, source: "PANEL", status: "active" }); if (error) return toast.error("Não foi possível cadastrar", { description: error.message }); toast.success("Cliente fictício cadastrado"); setOpen(false); await reload(); };
  return <div className="space-y-5"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="pl-9" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por nome, ID ou CPF" /></div><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus />Novo cliente</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Novo cliente fictício</DialogTitle></DialogHeader><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><Field label="Nome"><Input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><Field label="CPF de teste"><Input required value={form.cpf} onChange={(e) => setForm({ ...form, cpf: e.target.value })} placeholder="000.000.000-00" /></Field><Field label="Telefone"><Input required value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></Field><Field label="E-mail"><Input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></Field><Field label="CEP"><Input value={form.cep} onChange={(e) => setForm({ ...form, cep: e.target.value })} /></Field><Field label="Cidade"><Input value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} /></Field><Field label="Bairro"><Input value={form.neighborhood} onChange={(e) => setForm({ ...form, neighborhood: e.target.value })} /></Field><Field label="Endereço"><Input value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} /></Field><DialogFooter className="sm:col-span-2"><Button type="submit">Cadastrar cliente</Button></DialogFooter></form></DialogContent></Dialog></div><Card className="rounded-lg shadow-sm"><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>ID</TableHead><TableHead>Cliente</TableHead><TableHead>CPF</TableHead><TableHead>Telefone</TableHead><TableHead>Cidade</TableHead><TableHead>Status</TableHead><TableHead>Origem</TableHead></TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={row.id}><TableCell className="font-mono text-xs">{row.external_id}</TableCell><TableCell><div className="font-medium">{row.name}</div><div className="text-xs text-muted-foreground">{row.email ?? "Sem e-mail"}</div></TableCell><TableCell>{row.cpf ?? "—"}</TableCell><TableCell>{row.phone ?? "—"}</TableCell><TableCell>{row.city ?? "—"}</TableCell><TableCell><StatusBadge value={row.status} /></TableCell><TableCell>{row.source}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div>;
}

function ContractsView({ rows, customerName, planName }: { rows: Contract[]; customerName: (v: string) => string; planName: (v: string) => string }) { return <DataCard headers={["Contrato", "Cliente", "Plano", "Mensalidade", "Vencimento", "Status"]}>{rows.map((r) => <TableRow key={r.id}><TableCell className="font-mono text-xs">{r.external_id}</TableCell><TableCell>{customerName(r.customer_id)}</TableCell><TableCell>{planName(r.plan_id)}</TableCell><TableCell>{money.format(r.monthly_price)}</TableCell><TableCell>Dia {r.due_day}</TableCell><TableCell><StatusBadge value={r.status} /></TableCell></TableRow>)}</DataCard>; }
function PlansView({ rows }: { rows: Plan[] }) { return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{rows.map((p) => <Card key={p.id} className="rounded-lg shadow-sm"><CardHeader><div className="flex justify-between"><Signal className="size-5 text-primary" /><StatusBadge value={p.active ? "active" : "inactive"} /></div><CardTitle className="pt-4 text-lg">{p.name}</CardTitle></CardHeader><CardContent><div className="text-3xl font-semibold">{p.download_mbps >= 1000 ? "1 Giga" : `${p.download_mbps} Mega`}</div><p className="mt-1 text-sm text-muted-foreground">Upload de {p.upload_mbps} Mbps</p><p className="mt-5 text-xl font-semibold">{money.format(p.monthly_price)}<span className="text-xs font-normal text-muted-foreground">/mês</span></p><p className="mt-4 text-xs font-mono text-muted-foreground">{p.external_id}</p></CardContent></Card>)}</div>; }
function DataCard({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <Card className="rounded-lg shadow-sm"><CardContent className="p-0"><Table><TableHeader><TableRow>{headers.map((h) => <TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{children}</TableBody></Table></CardContent></Card>; }

function InvoicesView({ rows, customerName, reload }: { rows: Invoice[]; customerName: (v: string) => string; reload: () => Promise<void> }) {
  const pay = async (row: Invoice) => { const { error } = await supabase.from("invoices").update({ status: "paid", paid_at: new Date().toISOString() }).eq("id", row.id); if (error) toast.error("Falha na simulação"); else { toast.success("Pagamento fictício confirmado"); await reload(); } };
  return <DataCard headers={["Fatura", "Cliente", "Vencimento", "Valor", "Status", "Teste"]}>{rows.map((r) => <TableRow key={r.id}><TableCell className="font-mono text-xs">{r.external_id}</TableCell><TableCell>{customerName(r.customer_id)}</TableCell><TableCell>{date(r.due_date)}</TableCell><TableCell className="font-medium">{money.format(r.amount)}</TableCell><TableCell><StatusBadge value={r.status} /></TableCell><TableCell>{["open", "overdue"].includes(r.status) ? <Button size="sm" variant="outline" onClick={() => pay(r)}>Simular pagamento</Button> : <span className="text-xs text-muted-foreground">—</span>}</TableCell></TableRow>)}</DataCard>;
}

function TicketsView({ rows, customers, customerName, reload }: { rows: Ticket[]; customers: Customer[]; customerName: (v: string) => string; reload: () => Promise<void> }) {
  const [open, setOpen] = useState(false); const [form, setForm] = useState({ customer_id: "", category: "technical", priority: "normal", description: "" });
  const create = async (e: FormEvent) => { e.preventDefault(); const { error } = await supabase.from("tickets").insert({ customer_id: form.customer_id, category: form.category as Tables["tickets"]["Insert"]["category"], priority: form.priority as Tables["tickets"]["Insert"]["priority"], description: form.description }); if (error) toast.error("Não foi possível abrir o chamado", { description: error.message }); else { toast.success("Chamado aberto"); setOpen(false); await reload(); } };
  const status = async (id: string, value: string) => { await supabase.from("tickets").update({ status: value as Tables["tickets"]["Update"]["status"] }).eq("id", id); await reload(); };
  return <div className="space-y-5"><div className="flex justify-end"><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus />Novo chamado</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Abrir chamado fictício</DialogTitle></DialogHeader><form onSubmit={create} className="grid gap-4"><Field label="Cliente"><Select value={form.customer_id} onValueChange={(v) => setForm({ ...form, customer_id: v })}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{customers.map((c) => <SelectItem key={c.id} value={c.id}>{c.name} · {c.external_id}</SelectItem>)}</SelectContent></Select></Field><div className="grid grid-cols-2 gap-4"><Field label="Categoria"><Select value={form.category} onValueChange={(v) => setForm({ ...form, category: v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["technical","financial","commercial","installation","cancellation","other"].map((v) => <SelectItem key={v} value={v}>{labels[v]}</SelectItem>)}</SelectContent></Select></Field><Field label="Prioridade"><Select value={form.priority} onValueChange={(v) => setForm({ ...form, priority: v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["low","normal","high","urgent"].map((v) => <SelectItem key={v} value={v}>{labels[v]}</SelectItem>)}</SelectContent></Select></Field></div><Field label="Descrição"><Textarea required minLength={3} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field><DialogFooter><Button type="submit">Abrir chamado</Button></DialogFooter></form></DialogContent></Dialog></div><DataCard headers={["Protocolo", "Cliente", "Categoria", "Prioridade", "Descrição", "Status"]}>{rows.map((r) => <TableRow key={r.id}><TableCell className="font-mono text-xs">{r.protocol}</TableCell><TableCell>{customerName(r.customer_id)}</TableCell><TableCell>{labels[r.category]}</TableCell><TableCell><StatusBadge value={r.priority} /></TableCell><TableCell className="max-w-xs truncate">{r.description}</TableCell><TableCell><Select value={r.status} onValueChange={(v) => status(r.id, v)}><SelectTrigger className="w-36"><SelectValue /></SelectTrigger><SelectContent>{["open","in_progress","resolved","cancelled"].map((v) => <SelectItem key={v} value={v}>{labels[v]}</SelectItem>)}</SelectContent></Select></TableCell></TableRow>)}</DataCard></div>;
}

function CoverageView({ rows, plans, reload }: { rows: Coverage[]; plans: Plan[]; reload: () => Promise<void> }) {
  const [open, setOpen] = useState(false); const [form, setForm] = useState({ cep: "", city: "São Carlos", state: "SP", neighborhood: "", covered: true });
  const save = async (e: FormEvent) => { e.preventDefault(); const available_plans: Json = form.covered ? plans.filter((p) => p.active).map((p) => p.external_id) : []; const { error } = await supabase.from("coverage").insert({ ...form, available_plans }); if (error) toast.error("Não foi possível cadastrar", { description: error.message }); else { toast.success("Área fictícia cadastrada"); setOpen(false); await reload(); } };
  return <div className="space-y-5"><div className="flex justify-end"><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus />Nova área</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Cadastrar cobertura fictícia</DialogTitle></DialogHeader><form onSubmit={save} className="grid gap-4"><div className="grid grid-cols-2 gap-4"><Field label="CEP"><Input required value={form.cep} onChange={(e) => setForm({ ...form, cep: e.target.value })} /></Field><Field label="Estado"><Input required maxLength={2} value={form.state} onChange={(e) => setForm({ ...form, state: e.target.value.toUpperCase() })} /></Field></div><Field label="Cidade"><Input required value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} /></Field><Field label="Bairro"><Input required value={form.neighborhood} onChange={(e) => setForm({ ...form, neighborhood: e.target.value })} /></Field><div className="flex items-center justify-between rounded-md border p-3"><Label>Cobertura disponível</Label><Switch checked={form.covered} onCheckedChange={(v) => setForm({ ...form, covered: v })} /></div><DialogFooter><Button type="submit">Cadastrar área</Button></DialogFooter></form></DialogContent></Dialog></div><DataCard headers={["CEP", "Cidade", "Bairro", "Cobertura", "Planos disponíveis"]}>{rows.map((r) => <TableRow key={r.id}><TableCell className="font-mono">{r.cep}</TableCell><TableCell>{r.city}/{r.state}</TableCell><TableCell>{r.neighborhood}</TableCell><TableCell><Badge variant="outline" className={r.covered ? "border-success/25 bg-success/15 text-success" : "border-destructive/20 bg-destructive/10 text-destructive"}>{r.covered ? "SIM" : "NÃO"}</Badge></TableCell><TableCell className="text-xs text-muted-foreground">{Array.isArray(r.available_plans) ? r.available_plans.join(", ") || "—" : "—"}</TableCell></TableRow>)}</DataCard></div>;
}

const endpoints = [{ method: "GET", path: "/health", text: "Estado público do serviço" }, { method: "GET", path: "/customers/{external_id}", text: "Consultar cliente" }, { method: "GET", path: "/customers/{external_id}/invoices/open", text: "Segunda via em aberto" }, { method: "POST", path: "/coverage/check", text: "Consultar cobertura cadastrada" }, { method: "POST", path: "/tickets", text: "Abrir chamado" }, { method: "POST", path: "/sales/complete", text: "Concluir venda fictícia" }, { method: "POST", path: "/webhooks/ghl", text: "Receber evento do GHL" }];
function ApiView() { const base = typeof window === "undefined" ? "/api/public/v1" : `${window.location.origin}/api/public/v1`; const copy = (v: string) => void navigator.clipboard.writeText(v).then(() => toast.success("Copiado")); return <div className="space-y-5"><Card className="rounded-lg shadow-sm"><CardContent className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><Badge variant="outline">v1</Badge><span className="text-sm font-medium">Base URL</span></div><code className="mt-2 block break-all text-sm text-muted-foreground">{base}</code></div><Button size="sm" variant="outline" onClick={() => copy(base)}><Copy />Copiar</Button></CardContent></Card><div className="rounded-md border border-warning/25 bg-warning/10 p-4 text-sm"><strong>Autenticação obrigatória.</strong> Use <code>Authorization: Bearer &lt;SUA_TEST_KEY&gt;</code>. A chave real não é exibida nem armazenada nesta tela.</div><DataCard headers={["Método", "Endpoint", "Uso", ""]}>{endpoints.map((e) => <TableRow key={e.path}><TableCell><Badge variant={e.method === "POST" ? "default" : "outline"}>{e.method}</Badge></TableCell><TableCell className="font-mono text-xs">{e.path}</TableCell><TableCell>{e.text}</TableCell><TableCell className="text-right"><Button size="icon" variant="ghost" aria-label={`Copiar ${e.path}`} onClick={() => copy(e.path)}><Copy /></Button></TableCell></TableRow>)}</DataCard><div className="flex justify-end"><Button variant="outline" asChild><a href="/api-docs" target="_blank"><BookOpen />Abrir documentação completa</a></Button></div></div>; }
function LogsView({ rows }: { rows: ApiLog[] }) { const [selected, setSelected] = useState<ApiLog | null>(null); return <><DataCard headers={["Data", "Método", "Endpoint", "HTTP", "Tempo"]}>{rows.map((r) => <TableRow key={r.id} className="cursor-pointer" onClick={() => setSelected(r)}><TableCell>{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "medium" }).format(new Date(r.created_at))}</TableCell><TableCell><Badge variant="outline">{r.method}</Badge></TableCell><TableCell className="font-mono text-xs">{r.endpoint}</TableCell><TableCell><span className={r.status_code < 400 ? "text-success" : "text-destructive"}>{r.status_code}</span></TableCell><TableCell>{r.duration_ms} ms</TableCell></TableRow>)}</DataCard><Dialog open={Boolean(selected)} onOpenChange={(v) => !v && setSelected(null)}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>Detalhes da chamada</DialogTitle></DialogHeader><div className="grid gap-4 md:grid-cols-2"><JsonBox label="Request" value={selected?.request_body} /><JsonBox label="Response" value={selected?.response_body} /></div></DialogContent></Dialog></>; }
function JsonBox({ label, value }: { label: string; value: unknown }) { return <div><Label>{label}</Label><pre className="mt-2 max-h-80 overflow-auto rounded-md bg-code p-4 text-xs text-code-foreground">{JSON.stringify(value, null, 2) ?? "—"}</pre></div>; }

function SimulatorView({ data, toggleErp }: { data: AppData; toggleErp: (v: boolean) => void }) {
  const [kind, setKind] = useState("coverage"); const [key, setKey] = useState(""); const [input, setInput] = useState("13560000"); const [result, setResult] = useState<{ status: number; time: number; body: unknown } | null>(null); const [busy, setBusy] = useState(false);
  const run = async () => { if (!key) return toast.error("Informe sua chave de teste para esta chamada"); setBusy(true); const start = performance.now(); let path = "/coverage/check"; let method = "POST"; let body: unknown = { cep: input }; if (kind === "customer") { path = `/customers/${input}`; method = "GET"; body = undefined; } if (kind === "invoices") { path = `/customers/${input}/invoices/open`; method = "GET"; body = undefined; } if (kind === "error") { path = "/simulation/api-error"; body = { type: input || "500" }; } try { const response = await fetch(`/api/public/v1${path}`, { method, headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: body ? JSON.stringify(body) : undefined }); const text = await response.text(); let parsed: unknown = text; try { parsed = JSON.parse(text); } catch { /* intentionally display invalid JSON */ } setResult({ status: response.status, time: Math.round(performance.now() - start), body: parsed }); } catch { setResult({ status: 0, time: Math.round(performance.now() - start), body: { error: "NETWORK_ERROR" } }); } setBusy(false); };
  return <div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><Card className="rounded-lg shadow-sm"><CardHeader><CardTitle className="text-base">Montar teste</CardTitle></CardHeader><CardContent className="space-y-4"><Field label="Operação"><Select value={kind} onValueChange={(v) => { setKind(v); setInput(v === "coverage" ? "13560000" : v === "error" ? "500" : data.customers[0]?.external_id ?? "CLI-1001"); }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="coverage">Consultar cobertura</SelectItem><SelectItem value="customer">Consultar cliente</SelectItem><SelectItem value="invoices">Consultar fatura aberta</SelectItem><SelectItem value="error">Simular erro</SelectItem></SelectContent></Select></Field><Field label="Chave de teste"><Input type="password" autoComplete="off" value={key} onChange={(e) => setKey(e.target.value)} placeholder="Usada somente nesta chamada" /></Field><Field label={kind === "coverage" ? "CEP" : kind === "error" ? "Tipo: 500, 404, 401, timeout ou invalid_json" : "ID externo do cliente"}><Input value={input} onChange={(e) => setInput(e.target.value)} /></Field><Button className="w-full" disabled={busy} onClick={run}><Activity />{busy ? "Executando..." : "Executar chamada"}</Button><div className="flex items-center justify-between rounded-md border p-3"><div><p className="text-sm font-medium">Forçar ERP offline</p><p className="text-xs text-muted-foreground">Retorna HTTP 503 na API</p></div><Switch checked={!data.erpOnline} onCheckedChange={(v) => toggleErp(!v)} /></div></CardContent></Card><Card className="rounded-lg shadow-sm"><CardHeader><CardTitle className="text-base">Resultado</CardTitle></CardHeader><CardContent>{result ? <div className="space-y-4"><div className="flex gap-3"><Badge variant="outline" className={result.status < 400 ? "text-success" : "text-destructive"}>HTTP {result.status}</Badge><Badge variant="outline">{result.time} ms</Badge></div><JsonBox label="Response" value={result.body} /></div> : <div className="grid min-h-72 place-items-center text-center text-sm text-muted-foreground"><div><Code2 className="mx-auto mb-3 size-8 opacity-40" /><p>Execute uma chamada para ver<br />status, tempo e resposta.</p></div></div>}</CardContent></Card></div>;
}